### ISSUE TITLE
Come here to say

### ISSUE THREAD

**Issue by roachsinai** [ApproximateIdentity/website#1]
Thanks for you posts! Help a lot :)

**Comment by ApproximateIdentity** [comment]
Which posts are you referring to? Regardless, thanks a lot for the nice message! :)

edit: Sorry I got super confused by github's message and didn't realize you opened this in my website's issues. Obviously you must be talking about the website itself. Now I feel pretty silly for not understanding. In any case thanks so much for your kind message!

**Comment by roachsinai** [comment]
Yeah, I mean all those three posts and one video on Youtube listed at https://thomasnyberg.com . They are very helpful!

**Comment by ApproximateIdentity** [comment]
That's great! I guess the only thing I would add to those videos that it's probably best to use something like pybind11 or possibly in the future hpy ( https://github.com/hpyproject/hpy ) so you don't have to deal with the C-api interface directly yourself. My posts and videos were mostly meant to explain the C-api side of things (at the time mostly because that's what I personally wanted to understand better), but really it tends to be better to focus on a higher level. Then again, if you understand the basics, then you can understand what something like pybind11 is doing (just expand the preprocessor and look at the code that's generated and you'll see how it calls the C-api). It's not magic and it shouldn't seem like it! Also if you understand this stuff, you understand in which ways the GIL is a problem (and why most people's complaints about it are unfounded).

Anyway thanks a lot! My stuff is a bit old at this point, so you'll probably be able to find more useful and up-to-date info elsewhere. But I'm glad I could be of help. :)

**Comment by roachsinai** [comment]
I think your post did help me understand well about gil, the two macros: `Py_BEGIN_ALLOW_THREADS` and `Py_END_ALLOW_THREADS`. Like gil make python run bytecode safety, and if you make sure your code is safty, you could release gil to get better performance, after that code run just stay here to acquire gil to go back to a fake multithread program again.
